name: Deploy Skynet

on:
  push:
    branches:
      - master  # Change to your deployment branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
 
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-codeql: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t digitalsamba376/skynet:latest .
          docker tag digitalsamba376/skynet:latest digitalsamba376/skynet:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push digitalsamba376/skynet:latest
          docker push digitalsamba376/skynet:${{ github.sha }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker logout  # Logout to clear old credentials
            docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"

            sudo docker pull digitalsamba376/skynet:latest
            

            sudo docker stop skynet-dev || true
            sudo docker rm skynet-dev || true
            sudo docker stop redis || true
            sudo docker rm redis || true
            sudo docker run -d --name redis -p 6379:6379 redis 

            sudo docker run -d --name skynet-dev --gpus all \
                                -v /opt/models:/models \
                                --env-file /opt/dev/.env \
                                --link redis \
                                -p 8000:8000 digitalsamba376/skynet:latest
